version: '3'

services:

  web:
    image: nginx:mainline-alpine
    restart: always
    depends_on:
      - php
    volumes:
      - ./project:/project
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '90:80'
  php:
    build: ./docker/php
    environment:
      TZ: ${TZ}
    volumes:
      - ./project:/project
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    depends_on:
      - db

  elasticsearch:
    build:
      context: ./docker
      dockerfile: elasticsearch/Dockerfile
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD_FILE=/run/secrets/bootstrapPassword.txt
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
      - ./config/es/bootstrapPassword.txt:/run/secrets/bootstrapPassword.txt
    ports:
      - '9200:9200'
      - '9300:9300'

  db:
    image: mariadb:10.3.30-focal
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: toor
      TZ: ${TZ}
    volumes:
      - ./config/mysql.cnf:/etc/mysql/conf.d/local.cnf
      - ./data/db:/var/lib/mysql
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    links:
      - db:db
    environment:
      - ADMINER_DESIGN=nette
    volumes:
      - ./config/adminer.ini:/usr/local/etc/php/conf.d/uploads.ini
